CarRental/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarRental.Models
{
    public class Car
    {
        public int CarId { get; set; }
        public int CategoryId { get; set; }
        [Required(ErrorMessage = "Wprowadz nazwe producenta")]
        [StringLength(100, ErrorMessage="Nazwa producenta nie może mieć wiecej niż 100 znaków")]
        public string Producer { get; set; }
        [Required(ErrorMessage = "Wprowadz nazwe modelu pojazdu")]
        [StringLength(100, ErrorMessage = "Modelu pojazdu nie może mieć wiecej niż 100 znaków")]
        public string Model { get; set; }
        [Required(ErrorMessage = "Wprowadz pojemność pojazdu")]
        [Range(0.00, 50.00, ErrorMessage="Pojemność powinna mieścić sie w przedziale 0.00 - 50.0")]
        [DisplayFormat(DataFormatString = "{0:N}", ApplyFormatInEditMode = true)]
        public double EngineCapacity { get; set; }
        [Required(ErrorMessage = "Wprowadz przebieg pojazdu")]
        [Range(0.00, 1000000.00, ErrorMessage="Przebieg powinna mieścić sie w przedziale 0.00 - 50.0")]
        public double Mileage { get; set; }
        public string Color { get; set; }
        [StringLength(100, ErrorMessage="Nazwa pliku nie może mieć wiecej niż 100 znaków")]
        [FileExtensions(Extensions="png,jpg", ErrorMessage="Plik musi zawierać rozszerzenie png lub jpg")]
        public string PhotoUrl { get; set; }
        public DateTime ProductionDate { get; set; }
        public bool IsAvailable { get; set; }
        public bool IsUsed { get; set; }
        [Required(ErrorMessage = "Podaj cenę za kilometr")]
        [Range(0.00, 9999.99, ErrorMessage = "Cena musi mieścić sie w przedziale 0.00 - 9999.99")]
        [DisplayFormat(DataFormatString = "{0:N}", ApplyFormatInEditMode = true)]
        public decimal CostPerDay { get; set; }
        public DateTime? DateAdded { get; set; }
        public DateTime? LastUpdate { get; set; }

        public virtual Category Category { get; set; }
    }
}

CarRental/Controllers/CarController.cs
using CarRental.App_Start;
using CarRental.DAL;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using CarRental.Infrastructure;
using CarRental.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarRental.Controllers
{
    public class CarController : Controller
    {
        CarRentalContext db;
        private ApplicationUserManager _userManager;

        public CarController(CarRentalContext db)
        {
            this.db = db;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }


        public ActionResult List(string categoryName, string searchQuery = null)
        {
            IEnumerable<Car> cars;
            bool isAdmin = User.IsInRole("Admin");

            if (categoryName == null || categoryName.ToUpper() == "ALL")
            {
                cars = db.Cars;
            }
            else
            {
                var category = db.Categories
                    .Include("Cars")
                    .Where(cat => cat.CategoryName.ToUpper() == categoryName.ToUpper())
                    .Single();
                cars = category.Cars;
            }

            if (isAdmin)
            {
                cars = cars
                .Where(car => ((searchQuery == null
                    || car.Producer.ToLower().Contains(searchQuery.ToLower())
                    || car.Model.ToLower().Contains(searchQuery.ToLower())))
                );
            }
            else
            {
                 cars = cars
                .Where(car => ((searchQuery == null
                    || car.Producer.ToLower().Contains(searchQuery.ToLower())
                    || car.Model.ToLower().Contains(searchQuery.ToLower()))
                    && car.IsAvailable
                    && !car.IsUsed)
                );
            }

            if (Request.IsAjaxRequest())
            {
                return PartialView("_Cars", cars);
            }
            return View(cars);
        }

        [ChildActionOnly]
        [OutputCache(Duration = 60000)]
        public ActionResult CategoriesMenu()
        {
            var categories = db.Categories.ToList();
            return PartialView("_CarCategories", categories);
        }

        public ActionResult Details(int id)
        {
            var car = db.Cars
                .Where(x => x.CarId == id)
                .Single();
            return View(car);
        }

        public ActionResult FindName(string term)
        {
            var cars = db.Cars
                .Where(car => !car.IsUsed && car.IsAvailable && car.Model.ToLower().Contains(term.ToLower()))
                .Take(5)
                .Select(car => new { label = car.Model });
            return Json(cars, JsonRequestBehavior.AllowGet);
        }
    }
}

CarRental/Controllers/HistoryController.cs
using CarRental.App_Start;
using CarRental.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using CarRental.Models;

namespace CarRental.Controllers
{
    public class HistoryController : Controller
    {
        private CarRentalContext db;

        public HistoryController(CarRentalContext db)
        {
            this.db = db;
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Index(int CarId)
        {
            IEnumerable<Order> history = db.Orders
                .Where(o => o.Car.CarId == CarId)
                .OrderByDescending(o => o.DateCreated);

            return View(history);
        }






    }
}

CarRental/Views/Car/Details.cshtml
@model CarRental.Models.Car

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav>
    <ul class="nav-list">
        @Html.Action("CategoriesMenu")
    </ul>
</nav>

<section>
    <div class="content-container">
        <div class="content-detail">
            <div class="detail-image">
                <img src="@Path.Combine("/Content/Cars/", Model.PhotoUrl)"
                     alt="@string.Format("zdjęcie-przedstawia-{0}-{1}", Model.Producer.ToLower(), Model.Model.ToLower())" class="detail-image" />
            </div>
            <div class="detail-description">
                <div class="data-table-description">
                    <div class="detail-title">@string.Format("{0} {1}", Model.Producer, Model.Model)</div>
                    <div>Typ: @Model.Category.CategoryName</div>
                    <div>Przebieg: @string.Format("{0}", Model.Mileage)</div>
                    <div>Rok produkcji: @string.Format("{0:yyyy}", Model.ProductionDate)</div>
                    <div>Kolor: @Model.Color</div>
                    <div>Pojemność: @string.Format("{0:0.##}", Model.EngineCapacity)</div>
                    <div>Dostepny: @Model.IsAvailable</div>
                    <div>Cena: @string.Format("{0:0.##}", Model.CostPerDay)</div>
                    <div>Data zakupu: @string.Format("{0:dd-MM-yyyy}", Model.DateAdded)</div>

                    <div class="detail-buttons">
                        @if (!Model.IsUsed && Model.IsAvailable)
                        {
                            <div class="detail-button">
                                <a href="@Url.Action("BookIt", "Realization", new { id = Model.CarId })">Zarezerwuj</a>
                            </div>
                        }
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin") && !Model.IsUsed)
                        {
                            <div class="detail-button">
                                <a href="@Url.Action("AddCar", "Manage", new { CarId = Model.CarId })">Edytuj</a>
                            </div>
                            <div class="detail-button">
                                <a href="@Url.Action("HideCar", "Manage", new { CarId = Model.CarId })">Pokaż/Ukryj</a>
                            </div>
                        }
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <div class="detail-button">
                                <a href="@Url.Action("Index", "History", new { CarId = Model.CarId })">Historia pojazdu</a>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

CarRental/Views/Car/List.cshtml
@model IEnumerable<CarRental.Models.Car>

@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<nav>
    <ul class="nav-list">
        @Html.Action("CategoriesMenu")
    </ul>
</nav>

<section>
    <div class="content-container ">
        <div class="data-table-helper">

            <form id="search-form" method="get" class="table-helper-search" data-ajax="true" data-ajax-target="#carList">
                <input id="search-filter" type="search" name="searchQuery"
                       data-autocomplete-source="@Url.Action("FindName")"
                       placeholder="Wprowadź tekst, aby wyfiltrować..." />
                <input type="submit" value="" />
            </form>

        </div>

        <div id="carList">
            @Html.Partial("_Cars")
        </div>
    </div>
</section>


@section Scripts
{
    @System.Web.Optimization.Scripts.Render("~/bundles/jqueryAndJqueryUI")

    <script type="text/javascript">
        $(function () {

            var setupAutoComplete = function () {
                var $input = $(this);

                var options =
                    {
                        source: $input.attr("data-autocomplete-source"),
                        select: function (event, ui) {
                            $input = $(this);
                            $input.val(ui.item.label);
                            var $form = $input.parents("form:first");
                            $form.submit();
                        }
                    };

                $input.autocomplete(options);
            };

            var ajaxSubmit = function () {

                var $form = $(this);
                var settings = {
                    data: $(this).serialize(),
                    url: $(this).attr("action"),
                    type: $(this).attr("method")
                };

                $.ajax(settings).done(function (result) {
                    var $targetElement = $($form.data("ajax-target"));
                    var $newContent = $(result);
                    $($targetElement).replaceWith($newContent);
                    $newContent.effect("slide");
                });

                return false;
            };

            $("#search-filter").each(setupAutoComplete);
            $("#search-form").submit(ajaxSubmit);
        });
</script>



}

CarRental/Views/Car/_CarCategories.cshtml
@model IEnumerable<CarRental.Models.Category>


@foreach (var category in Model)
{
    
    <li class="nav-list-element">
        <a href="@Url.Action("List", "Car", new { categoryName = category.CategoryName.ToLower() })">
            @category.CategoryName
        </a>
    </li>
}

CarRental/Views/Car/_Cars.cshtml
@model IEnumerable<CarRental.Models.Car>

<div id="carList">
    <table id="data-table">
        @foreach (var car in Model)
        {
            <tr>

                <td>
                    <a href="@Url.Action("Details", "Car", new { id = car.CarId })" class="data-table-img">
                        <img src="@Path.Combine("/Content/Cars/", car.PhotoUrl)"
                             alt="@string.Format("zdjęcie-przedstawia-{0}-{1}", car.Producer.ToLower(), car.Model.ToLower())" class="data-table-img" />
                    </a>
                    <a class="data-table-description" href="@Url.Action("Details", "Car", new { id = car.CarId })">
                        <h1>
                            @car.Producer - @car.Model
                            @if (!car.IsAvailable)
                            {
                                <span style="color: red;">[UKRYTY]</span>
                            }
                            else if (car.IsUsed)
                            {
                                <span style="color: greenyellow;">[W UŻYCIU]</span>
                            }
                        </h1>
                        
                        <div>
                            <span>Przebieg: @String.Format("{0:0.##}", car.Mileage) </span>
                            <span>Rok produkcji: @String.Format("{0:MM-yyy}", car.ProductionDate)</span>
                            <span>Kolor: @car.Color</span>
                            <span>Pojemność: @car.EngineCapacity</span>
                            <span>Cena za dzień: @String.Format("{0:0.##zł}", car.CostPerDay)</span>
                        </div>
                    </a>
                </td>

            </tr>
        }
    </table>
</div>